### ISSUE TITLE
Making this more general so Vite, Astro could build their devtools on top?

### ISSUE THREAD

**Issue by nksaraf** [nuxt/devtools#140]
Just an idea, but I love what you guys are doing with the devtools here. Since using tanstack query's in page devtools, I have loved this pattern. Nuxt Devtools is the most complete implementation of this vision. 

I wonder what would it take to build devtools similarly for Astro, vite, etc.

**Comment by antfu** [comment]
Thanks for bringing this up.

Nuxt DevTools is made with the **context of Nuxt**. Like pages, auto imports, nuxt hooks, storages, vue inspectors, etc. - they are all coupled with Nuxt/Vue. I'd say it's great because it's specialized. So making it general is out-of-scope at this moment.

However, we do hope to see more tools/frameworks having similar features and that's part of the reason we make this open source. Feel free to research our approach and take what you need to implement the devtools for your own tools. I am looking forward to seeing one day we could have many frameworks inspiring each other on how to present those data in more informative and fun ways.
