### ISSUE TITLE
__vite_ssr_import_0__.hasInjectionContext is not a function When install @nuxt/devtools in nuxt 3 

### ISSUE THREAD

**Issue by kammy1996** [nuxt/devtools#258]
My project was up and running until I installed @nuxt/devtools. I installed it using 
```
npx nuxi@latest devtools enable
``` 
It got installed and then I started getting the following ERROR and my project is not running. 

![image](https://github.com/nuxt/devtools/assets/56693465/0e3a6dec-8a43-4edb-8c97-3a9f1ad90704)

I tried installing it manually using
```
npm i -D @nuxt/devtools
```
But got the same ERROR. Can someone please help me with this issue? 

**Other info** 
Node version - v18.12.1
Nuxt Version - 3.4.1

**Comment by antfu** [comment]
Can you help to provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example)? Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)

**Comment by arashsheyda** [comment]
@kammy1996 what package manager are you using?
I got the same error when I used `pnpm` and I didn't have `shamefully-hoist=true` in my `.npmrc`.
(When this option is set to true, pnpm will attempt to hoist dependencies to the root of the project's node_modules directory. Hoisting means that instead of installing multiple copies of the same dependency at different levels of the dependency tree, pnpm will place all instances of the dependency in the root node_modules directory.)


not sure if this would help you or not, it's hard to tell without a reproduction.

**Comment by kammy1996** [comment]
@arashsheyda I am using NPM 
and I do have `shamefully-hoist=true` in my `.npmrc`

I am working on the reproduction, Will post in this thread once done

**Comment by hcijr6** [comment]
I'm struggling exactly with the same issue. I'm also using npm and Nuxt 3.5.3.

**Comment by kammy1996** [comment]
Thanks @smcmo it worked.
