### ISSUE TITLE
Authorization for VS Code integration does not do anything

### ISSUE THREAD

**Issue by fabiangfd** [nuxt/devtools#267]
Hi,

I am running Nuxt 3.5.3 with Devtools 0.6.0.
here are my devtool settings:

```
devtools: {
        enabled: true,
        vscode: {
            startOnBoot: true,
            enabled: true,
            mode: "local-serve",
        },
},
```
When visiting the VS Code Tab in the Devtools UI, I get the "Permission Required" message. In my terminal I get, the message

```
 Permission Request 
│                                                                                                     
│   A browser is requesting permissions of writing files and running commands from the DevTools UI.   
│   undefined                                                                                         
│                                                                                                     
│   Please open the following URL in the browser:                                                     
│   http://localhost:3003/__nuxt_devtools__/auth?token=DtH2VoXvXaVZ0rrplKjjRmsccd3Zo4Sw               
│                                                                                                    │
```
When I open the URL I get the message "Authorized! You can close this window now".
However, going back to my Nuxt App, the Devtools still show "waiting for authorization".

I have tested with the latest Chrome and Firefox. Same behavior.

Any help would be appreciated.

**Comment by HenrijsS** [comment]
I'm on Safari (Version 16.5 (18615.2.9.11.4)) and it just insta-closes the window that I open from the link and doesn't do anything.

When I go back to the devtools, it shows that auth failed. 

Afterwards it shows the button to create routes and I get this error when I click it:
```zsh
 ERROR  [nuxt-devtools] RPC error on executing "runWizard": wizard[name] is not a function                                              8:44:50 PM

  at Proxy.runWizard (node_modules/@nuxt/devtools/dist/chunks/module-main.mjs:722:26)
  at node_modules/birpc/dist/index.mjs:59:29
  at WebSocket.<anonymous> (node_modules/@nuxt/devtools/dist/chunks/module-main.mjs:7075:19)
  at WebSocket.emit (node:events:525:35)
  at WebSocket.emit (node:domain:489:12)                                                                                                8:44:45 PM
  at Receiver.receiverOnMessage (node_modules/vite/dist/node/chunks/dep-e8f070e8.js:58179:22)
  at Receiver.emit (node:events:513:28)
  at Receiver.emit (node:domain:489:12)
  at Receiver.dataMessage (node_modules/vite/dist/node/chunks/dep-e8f070e8.js:55944:14)
  at Receiver.getData (node_modules/vite/dist/node/chunks/dep-e8f070e8.js:55862:17)
```

**Comment by antfu** [comment]
Can you help check if there is `__nuxt_dev_token__` in your localStorage? Does the port match with your app?

**Comment by antfu** [comment]
@HenrijsS for `runWizard` it was a bug, thanks!

**Comment by HenrijsS** [comment]
> Can you help check if there is `__nuxt_dev_token__` in your localStorage? Does the port match with your app?

The token is in the LocalStorage and it matches the URL that I was running from the integrated VSCode terminal.

I navigated to the VSCode tab in the devtools and it told me that "It seems you don't have code-server installed."

I'm gonna try to follow the guide and see what I need to do from there.

**Comment by antfu** [comment]
@HenrijsS That's another bug that I haven't fixed yet. Since it's not related to this issue, can you create another for us to track on? Thanks

**Comment by Sandros94** [comment]
I noticed that the permission page in the vscode tab goes away only if I'm on `localhost:<nodePort>`. If I try to open teh vscode tab via `hostname.local<nodePort>` it warns me with the permission message regardeless if I open up the auth link or not. The need for this is because sometimes I would like to access it from the tablet connected to a custom vpn.
Since there is limited documentation on this how should we proceed?

More over: is it possible to use the vscode tunnel instead of setting up a new code-server? Lets say I'm working on the laptop, instead of tabbing back and forward between it and the browser, I would just open up the tunnel and access it in the devtools. Is it possible to do it or it works only via code-servers?

I saw [this reply in #38](https://github.com/nuxt/devtools/issues/38#issuecomment-1457914562), but then I don't understand why there is a tunnel option in the [devtools configs](https://github.com/nuxt/devtools/blob/b0e31c72c12094b11ea3dd7d818106eb43309f6f/packages/devtools-kit/src/_types/options.ts#L86).

**Comment by antfu** [comment]
The auth token is stored in the localStorage, which means if you are using a different domain, you will need to change the localhost domain to your custom one to make it work.

For VS Code tunneling, it's not working properly because vscode.dev has a CORS rule to forbid being embedded in iframe. I think there is anything we could do to fix it.

**Comment by Sandros94** [comment]
> The auth token is stored in the localStorage, which means if you are using a different domain, you will need to change the localhost domain to your custom one to make it work.

I've been trying to do it by myself, but I have to admit that I didn't understand where should I configure the domain. Are we talking about the baseURL for the nuxt project?

**Comment by antfu** [comment]
It should be improved in the latest version to provide the correct domain for auth. Feel free to bring it back if it still persists.
