### ISSUE TITLE
feat: support strict CSP

### ISSUE THREAD

**Issue by flauwekeul** [nuxt/devtools#463]
### 🆒 Your use case

In our Nuxt app we're using the nuxt-security module to setup a strict Content Security Policy, using [nonces](https://nuxt-security.vercel.app/security/headers#nonce-support). In short: the server must provide a response header (or meta tag) containing a different nonce per response and each script tag in the html must have a `nonce` attribute with the same value as the header. The same can apply to style and link tags btw, but that's not relevant here.

nuxt-security injects these `nonce` attributes in a `render:html` hook in a [nitro plugin](https://github.com/Baroshem/nuxt-security/blob/main/src/runtime/nitro/plugins/99-cspNonce.ts). But this doesn't happen for the nuxt devtools script (probably because it gets injected at runtime?) resulting in an error and a broken nuxt devtools.

### 🆕 The solution you'd like

I haven't looked into how the nuxt devtools script is injected, but if it could be configured to be injected server-side, the nuxt-security module should be able to automatically inject the `nonce` attribute in the `render:html` hook.

Another solution might be to add a hash to the CSP header and the script tag (in an `integrity` attribute), see https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/script-src#whitelisting_external_scripts_using_hashes. But again, something needs to be done server-side and I don't know if that's even possible for nuxt devtools.

### 🔍 Alternatives you've considered

Of course, it's possible to disable strict CSP during development, but this makes development too different from production environments. It would be really shitty to see all kinds of CSP errors on a test/acc/prod environment, while they should've been avoided during development.

**Comment by antfu** [comment]
I am happy to support that, but I have little experience with CSP. Would you help set up a minimal nuxt app with CSP enabled so we could work on getting the support? Thanks!

**Comment by flauwekeul** [comment]
Great, thanks! I'll make a repo next week.

**Comment by flauwekeul** [comment]
A minimal Nuxt app with [nuxt-security](https://nuxt-security.vercel.app/) configured to have strict CSP for `'script-src'` https://github.com/flauwekeul/nuxt-devtools-strict-csp. There are 2 problems:

1. The inline script added by the devtools doesn't have a nonce and is therefore not trusted.
2. Pressing Shift + Option + D shows an iframe with blocked content. This is also caused by nuxt-security, but not the strict CSP header. I haven't figured out yet what causes this. The default security rules that nuxt-security sets should permit iframes from the same origin...

**Comment by flauwekeul** [comment]
Did some more tinkering with a colleague who's better in debugging than I am. And this nuxt config "fixes" the issues:
```ts
// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
  devtools: { enabled: true },
  // 1.
  modules: ['@nuxt/devtools', 'nuxt-security'],
  security: {
    enabled: true,
    nonce: true,
    headers: {
      contentSecurityPolicy: {
        'script-src': ["'nonce-{{nonce}}'", "'strict-dynamic'"],
      },
      // 2.
      crossOriginEmbedderPolicy: false,
    },
  },
})
```

1. nuxt-security uses a nitro hook (`render:html`) to set the nonce attribute on all tags that require them (script tags in this case). Devtools uses the same hook to inject the script in the head. Without explicitly placing the nuxt-security module _after_ the @nuxt/devtools module, the nuxt-security hook runs first.
2. For reasons unknown to me, the browser interprets the devtools iframe as not from the same origin (i.e. cross-origin). The default nuxt-security policies are set to same-origin, so that's why the iframe contents are blocked. Disabling the [`crossOriginEmbedderPolicy` header](https://nuxt-security.vercel.app/security/headers#cross-origin-embedder-policy) (or setting it to the browser default of `unsafe-none`) fixes this. But the true problem seems to be why the browser thinks the iframe source is cross-origin...

**Comment by antfu** [comment]
I am able to fix 1. with c5e41da02bd0a88f9f31f0abd7e8c133f4372014.

But for 2. I am not sure if there is anything we could do. Would disabling `crossOriginEmbedderPolicy` in dev time a valid solution to you?

**Comment by flauwekeul** [comment]
Thanks for the fix 👍 

I was hoping you'd understand why the iframe source is considered cross-origin 🥲 But it doesn't seem like something that should be fixed in devtools.

**Comment by GalacticHypernova** [comment]
I might be able to help with 2 if it's still relevant @antfu , if you think it's worth it. Because if we're talking security wise, then yes, I think being able to use devtools in strict CSP mode would be worth it to have the most accurate representation of the application at production through dev mode.

**Comment by AlansCodeLog** [comment]
Ran into @flauwekeul's #2 and I had to so some digging to understand and find a fix. But basically what's happening is when you enable COEP, all iframes, even same origin iframes must be served with COEP but the iframe is not served with COEP. If you check in the network tab, chrome will tell you the header is missing. 

I'm not 100% sure why this is or why you can't set headers for the page using routeRules. It's acting like a public resource but I did a quick search through the module and I don't think it is?  The reason I say it's acting like a public resource is you can't add headers through nuxt to public resources when using the dev server. You must set the headers using vite (see https://github.com/nuxt/nuxt/issues/22141 and https://github.com/vitejs/vite/issues/3909#issuecomment-934044912).

As to *why* the iframe can't be embedded even if it's same origin and all the context behind that is very well explained in [this stackblitz blog](https://blog.stackblitz.com/posts/cross-browser-with-coop-coep/), specifically this part:

> Serving a document with the Cross-Origin-Embedder-Policy also impacts pages loaded through iframe. If the top-level document is served with COEP: require-corp, the document loaded inside the iframe should have the appropriate headers as well. This [example demonstrates a document loaded inside the iframe with appropriate headers](https://stackblitz.com/edit/coep-iframe-example?file=src%2Findex.html). The top-level document has the COEP header set and embeds two iframes. The first iframe loads [stackblitz.com](https://stackblitz.com/), which does not grant our document permission to load it. The second iframe loads a local file, served on the same origin. However, because the top-level document is served with COEP, the document loaded should also have the COEP header set. If the COEP header was not required on this document, it would get elevated permissions and would be able to load resources that could not be loaded by the top-level page itself. For that reason, the COEP header is required for same-origin documents loaded through an iframe.

Note their example is wrong and actually works  because I think they've accidentally served the iframe with COEP.

There are two solutions. The module can add credentialless to the iframe, I'm not sure if this is interferes with any functionality. Or users can set headers for `__nuxt_devtools__/client/modules/overview` in their vite config using the method I've linked.

See also:
- [the spec](https://html.spec.whatwg.org/multipage/document-sequences.html#creating-browsing-contexts%3Aconcept-document-coop)
- [#5 here](https://web.dev/articles/cross-origin-isolation-guide#mitigate_the_impact_of_cross-origin_isolation)
