### ISSUE TITLE
fix: Client side navigation while the payload tab is open causes errors in the console

### ISSUE THREAD

**Issue by CernyMatej** [nuxt/devtools#710]
### 🐛 The bug

When performing client side navigation with the `payload` tab open, the console starts getting flooded with the following errors:

<img width="515" alt="image" src="https://github.com/user-attachments/assets/c8a99c36-52b6-44cc-a09e-6bdd0015c8bd">

------------------------------
- Operating System: Linux
- Node Version:     v18.20.3
- Nuxt Version:     3.12.4
- CLI Version:      3.12.0
- Nitro Version:    2.9.7
- Package Manager:  npm@10.2.3
- Builder:          -
- User Config:      compatibilityDate, devtools
- Runtime Modules:  -
- Build Modules:    -
------------------------------

### 🛠️ To reproduce

https://stackblitz.com/edit/github-qufxkh?file=pages%2Findex.vue,pages%2Ffoo.vue

- open devtools
- open the payload tab
- click on the link to navigate to another page
- see the errors in the console

### 🌈 Expected behavior

No error messages in the console

**Comment by arashsheyda** [comment]
I can't reproduce this

**Comment by kheiner** [comment]
I am having the same issue as described, however the provided stackblitz isn't giving the same issue. The issue doesn't occur on initial SSR load, it only occurs on a CSR. The DevTools must be open and on the Payload tab (it also happens for me when I'm on the Runtime Config tab).

I ran `npx nuxi@latest init devtools-payload-error` and created a new `pages/index.vue` file with the following:
```vue
<script setup lang="ts">
const { data: todos } = await useAsyncData(
  'recursive-type-error-in-console-on-refresh-in-nuxt-devtools-payload',
  () => $fetch('https://jsonplaceholder.typicode.com/todos/1')
)
</script>

<template>
  <nuxt-link to="/">Trigger Issue</nuxt-link>
  {{ todos }}
</template>
```

You can either trigger the issue by the following steps:
1. Open Nuxt DevTools 
2. Tap the Cogwheel Icon for the `Runtime Configs module` *or* Tap the Dataset Icon for `Payload module`
3. If you're in the `Runtime Configs module` you can click the link to trigger the issue (initiate Client Side Render via Nuxt-link). If you're in the `Payload module` you can also re-fetch the data to trigger the issue.

It's helpful if you already have the console open because the errors bog down the inspector.

https://github.com/user-attachments/assets/251e5cbd-a2ba-4f6f-9330-17cd8a7b0176

**Comment by CernyMatej** [comment]
I can reproduce it on stackblitz.

https://github.com/user-attachments/assets/dd3ebd72-50ad-4066-9520-59e9a472a902

**Comment by arashsheyda** [comment]
thank you both!

**Comment by kdavid14** [comment]
apologies, this still occurs in my end using 1.6.0, I have a useFetch with watch array, when I open the payload data from the DevTools and the watch properties is changes and cause refetching the Type error will be triggered 

![Image](https://github.com/user-attachments/assets/550c49f2-07ea-4c77-81de-3129d63d2a8d)
